site_name: SITE NAME
repo_url: https://github.com/acceleratescience/REPO-TITLE
site_url: https://acceleratescience.github.io/REPO-TITLE/
nav:
  - Home: 
    - Welcome!: index.md
    - License: Home/LICENSE.md
    - About us: Home/about.md
  - Single Page 1: single.md
  - Multi Page 1:
    - Subpage 1: multi_1/subpage_1.md
    - Subpage 2: multi_1/subpage_2.md
  - Multi Page 2:
    - multi_2/index.md
    - Page 1: multi_2/subpage_1.md
    - Page 2: multi_2/subpage_2.md
  - Resources:
    - resources/index.md
    - Slides: resources/slides.md
    - Further reading: resources/references.md
theme:
  favicon: imgs/trace.svg
  name: material
  logo: imgs/trace.svg
  features:
    - search.suggest
    - search.highlight
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    annotation: material/chevron-right-circle 
plugins:
  - mkdocstrings
  - search
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra:
  consent:
      title: Cookie consent
      description: >- 
        We use cookies to recognize your repeated visits and preferences, as well
        as to measure the effectiveness of our documentation and whether users
        find what they're searching for. With your consent, you're helping us to
        make our documentation better.
      actions:
        - accept
        - reject
        - manage
  analytics:
    provider: google
    property: PROPERTY-ID
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/acceleratescience/REPO-TITLE/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/acceleratescience/REPO-TITLE/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.
copyright: >
  Copyright &copy; 2024 Accelerate Programme for Scientific Discovery –
  <a href="#__consent">Change cookie settings</a>
dev_addr: '0.0.0.0:8080'
watch:
  - .
